config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  root "welcome#index"
  get "welcome" => "welcome#index"
  get "abouts" => "abouts#index"
  resources :categories, :only => [:index, :show]
  resources :posts do
    member do
      post :collect
    end
    resources :subscriptions, :only => [:create, :destroy]
    resources :likes, :only => [:create, :destroy]
    resources :comments, :controller => "post_comments", :only => [:create, :destroy]
  end
  resources :users, :only => [:index] do
    resource :profile, :controller => "user_profiles", :only => [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :managements
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_postsships
  has_many :posts , :through => :category_postsships
end

app/models/category_postsship.rb
class CategoryPostsship < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments # @post = Post.find(xxx), @post.comments
  has_many :category_postsships
  has_many :categories, :through => :category_postsships
  has_many :likes
  has_many :like_users , :through=> :likes , :source => :user
  has_many :subscriptions
  has_many :subscriptions_users ,:through=> :subscriptions, :source =>:user

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  def countpeople
    if self.brower_people.nil?
      self.brower_people = 1
    else
      self.brower_people += 1
    end
    self.save
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,
         :omniauthable, :omniauth_providers => [:facebook]

   has_many :posts
   has_many :comments
   has_one  :profile
   has_many :likes
   has_many :like_posts , :through=> :likes , :source => :post
   has_many :subscriptions
   has_many :subscriptions_posts ,:through=> :subscriptions, :source =>:post
   has_many :friends

   def get_profile
      if self.profile
        self.profile
      else
        self.create_profile
      end
   end

  def short_name
    email.split("@").first
  end

   def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    like = @post.likes.find_by_user_id(current_user)
    if !like
      @like = @post.likes.create!(:user => current_user)
    end
    # 為什麼要create要!
    respond_to do |format|
      format.js { render "posts/like" }
    end
  end

  def destroy
    #@like = current_user.likes.find( params[:id] )
    @like = @post.likes.find_by_user_id(current_user.id)
    @like.destroy
    @like = nil # 這樣讓 topics/_like.html.erb 會顯示 Like 按鈕
    respond_to do |format|
      format.js { render "posts/like" }
    end
  end

  protected

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, :only => [:show, :destroy, :edit, :update]
  before_action :authenticate_user!, :only => [:new, :create, :destroy, :edit, :update]

  def index
    #Post.joins(:comments)
    #Post.select('posts.all, max(comments.created_at) as last_comment')
    #Post.group('posts.id')
    #Post.order('last_comment desc')
    @posts = Post.all
    if params[:sort] == "replytime"
      @posts = Post.order('last_comment desc, topics.created_at desc')
    elsif params[:sort] == "replys"
      @posts = Post.order('brower_people DESC, created_at DESC')
    elsif params[:sort] == "browers"
      @posts = Post.order('brower_people DESC, created_at DESC')
    else params[:sort] == "createtime"
      @posts = Post.order('id DESC')
    end
    @posts = @posts.page(params[:page]).per(20)
    # 要怎麼用find or where 找出is_public =>nil 和 false
  end

  def new
    @post = Post.new
    @category = Category.all
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
    @post.countpeople
    @post.save
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to user_profile_path(@post.user_id)
    if params[:destroy_logo]
      @event.logo = nil
      @event.save
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path(:page => params[:page])
  end

  def collect

  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name,:logo, :is_public, :description, :category_ids => [])
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

  before_action :find_user, :only => [:index, :show]
  before_action :set_my_user, :only => [:update, :destroy]
  before_action :authenticate_user!, :only => [:create, :new]

  def index
  end

  def show
    @posts = @user.posts.all
    @comments = @user.comments.all
    @profile = @user.get_profile
    @subscription = @user.subscriptions
    @userlikesss  = Post.where(:id => @user.likes.pluck(:post_id) )
  end

  def edit
    if current_user.admin
      @user = User.find(params[:user_id])
      @profile = @user.get_profile
    else
      @user = current_user
      @profile = @user.get_profile
    end
  end

  def update
    @profile = @user.get_profile
    if @user == current_user || current_user.admin
      if @profile.update(profile_params)
        redirect_to user_profile_path(@user)
      else
        render :new
      end
    end
  end

  def destroy
  end


  def find_user
    @user = User.find(params[:user_id])
  end

  def set_my_user
    @user = current_user
  end

  def profile_params
    params.require(:profile).permit(:description, :name, :email, :gender, :birthday)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/collect_helper.rb
module CollectHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/user_profiles/edit.html.erb
<h2><%= simple_format @user.username %></h2>

<%= form_for @profile, :url => user_profile_path(@user) do |f| %>

    <%= f.label :name, "NAME" %>
    <p>NAME : <%= f.text_field :name %></p>

    <%= f.label :email, "EMAIL" %>
    <p>EMAIL : <%= f.email_field :email %></p>

    <%= f.label :birthday, "BIRDAY" %>
    <p>BIRDAY :<%= f.datetime_select :birthday %> </p>

    <%= f.label :gender, "GENDER" %>
    <p><%= f.radio_button :gender, "male", :checked => 'true' %><span>Male</span>
      <%= f.radio_button :gender, "female" %><span>Female</span></p>

    <%= f.label :description, "DESCRIPTION" %>
    <p><%= f.text_area :description %> </p>

    <%= f.submit 'Update', :class => "btn btn-primary" %>
<% end %>

app/views/user_profiles/show.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= @user.username %></h1>

  <% if @user == current_user %>
      <%= link_to(t("modify"), edit_registration_path(:user), :class => "btn btn-default") %>
      <%= link_to "Edit my profile", edit_user_profile_path(current_user), :class => "btn btn-default" %>
      <%= link_to "NEW", new_post_path, :class => "btn btn-default" %>
  <% elsif current_user.admin %>
      <%= link_to "Edit ANY profile", edit_user_profile_path(params[:user_id]), :class => "btn btn-default" %>
  <% end %>
  </div>

  <p>NAME : <%= @profile.try(:name) %></p>
  <p>EMAIL : <%= @profile.try(:email) %></p>
  <p>GENDER : <%= @profile.try(:gender) %></p>
  <p>DESCRIPTION : <%= @profile.try(:description) %></p>

  <table class="table">
    <h3>我的最愛愛啦</h3>
    <% @subscription.each do |sub| %>
        <tr><td><%= link_to Post.find(sub.post_id).name, post_path(sub.post_id) %></td></tr>
    <% end %>
  </table>


    <table class="table">
      <h3>發過的文章</h3>
      <tr>
        <th>文章</th>
        <th>修改</th>
        <th>狀態</th>
      </tr>
      <% @user.posts.each do |f| %>
          <tr>
            <td>
              <%= link_to f.name, post_path(f) %>
            </td>
            <td>
              <%= link_to "EDIT", edit_post_path(f), :class => "btn btn-default" %>
            </td>
            <td>
              <% if f.is_public || f.is_public == nil %>
                  <span>發布</span>
              <% else %>
                  <span>草稿</span>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>

    <h3>讚過的文章：</h3>
  <table class="table">
    <% @userlikesss.each do |x| %>
       <tr><td><%= link_to x.name, post_path(x.id) %></td></tr>
  <% end %>
    </table>
</div>