config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  root "welcome#index"
  get "welcome" => "welcome#index"
  get "abouts" => "abouts#index"
  resources :categories, :only => [:index, :show]
  resources :posts do
    member do
      post :collect
    end
    resources :subscriptions, :only => [:create, :destroy]
    resources :likes, :only => [:create, :destroy]
    resources :comments, :controller => "post_comments", :only => [:create, :destroy]
  end
  resources :users, :only => [:index] do
    resource :profile, :controller => "user_profiles", :only => [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :managements
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_postsships
  has_many :posts , :through => :category_postsships
end

app/models/category_postsship.rb
class CategoryPostsship < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments # @post = Post.find(xxx), @post.comments
  has_many :category_postsships
  has_many :categories, :through => :category_postsships
  has_many :likes
  has_many :like_users , :through=> :likes , :source => :user
  has_many :subscriptions
  has_many :subscriptions_users ,:through=> :subscriptions, :source =>:user

  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  def countpeople
    if self.brower_people.nil?
      self.brower_people = 1
    else
      self.brower_people += 1
    end
    self.save
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable ,
         :omniauthable, :omniauth_providers => [:facebook]

   has_many :posts
   has_many :comments
   has_one  :profile
   has_many :likes
   has_many :like_posts , :through=> :likes , :source => :post
   has_many :subscriptions
   has_many :subscriptions_posts ,:through=> :subscriptions, :source =>:post
   has_many :friends

   def get_profile
      if self.profile
        self.profile
      else
        self.create_profile
      end
   end

  def short_name
    email.split("@").first
  end

   def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    like = @post.likes.find_by_user_id(current_user)
    if !like
      @like = @post.likes.create!(:user => current_user)
    end
    # 為什麼要create要!
    respond_to do |format|
      format.js { render "posts/like" }
    end
  end

  def destroy
    #@like = current_user.likes.find( params[:id] )
    @like = @post.likes.find_by_user_id(current_user.id)
    @like.destroy
    @like = nil # 這樣讓 topics/_like.html.erb 會顯示 Like 按鈕
    respond_to do |format|
      format.js { render "posts/like" }
    end
  end

  protected

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, :only => [:show, :destroy, :edit, :update]
  before_action :authenticate_user!, :only => [:new, :create, :destroy, :edit, :update]

  def index
    #Post.joins(:comments)
    #Post.select('posts.all, max(comments.created_at) as last_comment')
    #Post.group('posts.id')
    #Post.order('last_comment desc')
    @posts = Post.all
    if params[:sort] == "replytime"
      @posts = Post.order('last_comment desc, topics.created_at desc')
    elsif params[:sort] == "replys"
      @posts = Post.order('brower_people DESC, created_at DESC')
    elsif params[:sort] == "browers"
      @posts = Post.order('brower_people DESC, created_at DESC')
    else params[:sort] == "createtime"
      @posts = Post.order('id DESC')
    end
    @posts = @posts.page(params[:page]).per(20)
    # 要怎麼用find or where 找出is_public =>nil 和 false
  end

  def new
    @post = Post.new
    @category = Category.all
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
    @post.countpeople
    @post.save
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to user_profile_path(@post.user_id)
    if params[:destroy_logo]
      @event.logo = nil
      @event.save
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path(:page => params[:page])
  end

  def collect

  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name,:logo, :is_public, :description, :category_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/collect_helper.rb
module CollectHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_comment.html.erb
  <p id="comment-<%= comment.id %>" >
    <%= comment.name %>
    <%= link_to 'Delete', post_comment_path(@post, comment), :method => :delete, :class => "btn btn-danger" , :remote => true %>
  </p>

app/views/posts/_like.html.erb
<% if like %>
    <%= link_to "Unlike", post_like_path(@post, like), :remote => true, :method => :delete, :class => "btn btn-primary" %>
<% else %>
    <%= link_to "Like", post_likes_path(@post), :remote => true, :method => :post, :class => "btn btn-primary" %>
<% end %>

<% ids = @post.likes.pluck(:user_id) %>
<% name = User.where(:id => ids) %>
<span>讚過的人 : </span>
<% name.each do |x| %>
    <span class="label label-success"> <%= x.username %></span>
<% end %>

app/views/posts/_subscription.html.erb
<% if subscription %>
    <%= link_to "取消訂閱", post_subscription_path(@post, subscription),remote: true, :method => :delete, :class => "btn btn-primary" %>
<% else %>
    <%= link_to "訂閱", post_subscriptions_path(@post),remote: true, :method => :post, :class => "btn btn-primary" %>
<% end %>

app/views/posts/create.js.erb
$("#comments-list").prepend("<%=j render( :partial => "posts/comment", :locals => { :comment => @comment }  ) %>");
$("#new_comment").trigger('reset');

$("#like-area").html("<%=j render( :partial => "posts/like", :locals => { :like => @like } ) %>")

app/views/posts/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();
$("#like-area").html("<%= j render( :partial => "posts/like", :locals => { :like => @like } ) %>")

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
    </div>
    <div class="form-group">
      <%= f.radio_button :is_public, 'true', :checked => true %> <span>發布</span>
      <%= f.radio_button :is_public, 'false' %>
      <snan>草稿</snan>
    </div>

    <%= f.label :name, "TITLE" %>
    <%= f.text_field :name, :class => "form-control" %>

    <%= f.label :description, "DESCRIPTION" %>
    <%= f.text_area :description, :class => "form-control" %>

    <%= f.submit "ENTER", :class => "btn btn-primary " %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="text-center mbottom30">
  <h1>ALL POSTS</h1>
  <%= link_to "NEW", new_post_path, :class => "btn btn-default" %>
  <%= link_to "最後回覆時間", posts_path(:sort => "replytime"), :class => "btn btn-default"  %>
  <%= link_to "多人回覆", posts_path(:sort => "replys") , :class => "btn btn-default" %>
  <%= link_to "最多瀏覽數", posts_path(:sort => "browers") , :class => "btn btn-default" %>
  <%= link_to "最新文章", posts_path(:sort => "createtime"), :class => "btn btn-default"  %>
  </div>
  <table class="table table-hover">
    <tr>
      <th>文章名</th>
      <th>發文人</th>
      <th>回覆數</th>
      <th>刪除</th>
      <th>發文時間</th>
    </tr>
    <% @posts.each do |post| %>
        <tr>
          <% if post.is_public || post.is_public.nil? %>
              <td>
                <%= link_to "#{post.name}", post_path(post) %>
              </td>
              <td><%= post.user.try(:short_name) %></td>
              <td><%= post.comments.count %></td>
              <td>
                <%= link_to("DELETE", post_path(post, :page => params[:page]),
                            :method => :delete, :class => "btn btn-default") if (current_user.present? && post.user == current_user) || current_user.admin %>
              </td>
              <td><%= post.created_at %></td>
          <% end %>
        </tr>
    <% end %>
  </table>
<div class="text-center">
  <%= paginate @posts, :theme => 'twitter-bootstrap-3',:pagination_class => "pagination-sm" %>
</div>
</div>

app/views/posts/like.js.erb
$("#like-area").html("<%= j render( :partial => "posts/like", :locals => { :like => @like } ) %>")

app/views/posts/new.html.erb
<div class="container">
  <h1>POST NEW</h1>
  <%= form_for @post do |f| %>
      <%= collection_select(:post, :category_ids, Category.all, :id, :name, {:prompt => true}, {:class => "js-example-basic-single width50", :multiple => true}) %>
      <div class="form-group">
        <%= f.label :logo, "LOGO檔案" %>
        <%= f.file_field :logo %>
        <%= check_box_tag "destroy_logo", "1" %> 刪除檔案
      </div>
      <div class="form-group">
        <%= f.radio_button :is_public, 'true', :checked => true %> <span>發布</span>
        <%= f.radio_button :is_public, 'false' %>
        <snan>草稿</snan>
      </div>

      <div class="form-group width50">
        <%= f.label :name, "TITLE" %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
      <div class="form-group width50 height200">
        <%= f.label :description, "DESCRIPTION" %>
        <%= f.text_area :description, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "ENTER", :class => "btn btn-primary " %>
      </div>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class="container">

  <% subscription = @post.subscriptions.find_by_user_id(current_user) %>

  <div class="text-center mbottom30">
    <h1><%= @post.name %></h1>
    <% @post.categories.each do |category| %>
        <span class="label label-default">  <%= category.name %></span>
    <% end %>
  </div>
  <div class="row mbottom30">
    <div class="col-md-1">
      <div id="subscription">
        <%= render :partial => "subscription", :locals => {:subscription => subscription} %>
      </div>

    </div>
    <div class="col-md-3">
      <% like = @post.likes.find_by_user_id(current_user) %>
      <div id="like-area">
        <%= render :partial => "like", :locals => {:like => like} %>
      </div>
    </div>
    <div class="col-md-3 col-md-push-4">
      <span class="pull-right label label-success">瀏覽人次 : <%= @post.brower_people %></span>
      <span class="pull-right label label-success">點讚人次 :<%= @post.likes.count %></span>
    </div>
  </div>
  <!--要怎麼, :url => user_profile_path(@post.user) 讓每個名字倒回頁面 ｉｄ要怎麼改-->
  <% if @post.logo.exists? %>
      <%= image_tag(@post.logo(:medium)) %>
  <% end %>
  <div class="mupdown50">
    <p><%= @post.description %></p>
  </div>
  <%= form_for @comment, :url => post_comments_path(@post), :remote => true do |f| %>
      <%= f.label :name, "Comment" %><br>
      <%= f.text_field :name %>
      <%= f.submit "Enter", :class => "btn btn-default" %>
  <% end %>

  <div id="comments-list">
    <% @comments.each do |comment| %>
        <p id="comment-<%= comment.id %>">
          <%= comment.name %>
          <%= link_to 'Delete', post_comment_path(@post, comment), :method => :delete, :class => "btn btn-danger", :remote => true %>
        </p>
    <% end %>
  </div>

  <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
</div>

app/views/posts/subscription.js.erb
$("#subscription").html("<%=j render( :partial=>"posts/subscription" ,:locals => {:subscription => @subscription}) %>")